### ISSUE TITLE
Port

### ISSUE THREAD

**Issue by kostyaten** [matheusvanzan/sshpass-action#1]
How do I set the port?

**Comment by matheusvanzan** [comment]
Right now it uses the default SSH port. You can add arguments to sshpass in [entrypoint.sh](https://github.com/matheusvanzan/sshpass-action/blob/master/entrypoint.sh). 
I can add it as an optional argument later.

**Comment by matheusvanzan** [comment]
Right now it uses the default SSH port (22). You can add arguments to sshpass in [entrypoint.sh](https://github.com/matheusvanzan/sshpass-action/blob/master/entrypoint.sh).

```
sshpass -e ssh -o StrictHostKeyChecking=no -p your_port $USERNAME@$HOST "$CMD"
```

I can add it as an optional argument later.
